### ISSUE TITLE
Is it possible to draw custom objects(like smoke) using custom OpenGL 3.0 shader?

### ISSUE THREAD

**Issue by harshalkulkarni07** [Esri/arcgis-runtime-samples-qt#1050]
I am working on a project which uses ArcGIS Runtime SDK for Qt creator.
I want to draw custom objects like smoke on top of the earth environment provided by ESRI ArcGIS.
I tried to search through the documentation, but could not dig out a proper help.
Can someone please help me understand, whether it is possible to write our own OpenGL Shader?

**Comment by ldanzinger** [comment]
@harshalkulkarni07 this isn't something we expose the ability for in the SDK. The options I can think of are:

- display your customer objects above the map/scene view. You could possible use our `MapView::locationToSceen` method to get the vertices of the smoke polygon, and get screen coordinates out of that. You could then draw your custom object on your own in those screen coordinates. https://developers.arcgis.com/qt/latest/cpp/api-reference/esri-arcgisruntime-mapview.html#locationToScreen

- You wouldn't get any cool smoke effects, but you could simply draw polygon graphics in a GraphicsOverlay that represent the boundaries of the affected areas. We have a lot of styling options in the API like fill patterns, colors, etc, but nothing for cool animations like smoke...

Lastly, I'd suggest logging these types of questions in our forum "geonet" - https://community.esri.com/community/developers/native-app-developers/arcgis-runtime-sdk-for-qt.

**Comment by shrikant-panchal** [comment]
Thanks Lucas!
Sorry, but this is quite an urgent requirement.
I tried to put a query on "Geonet" portal, but did not receive any response yet.

**Could you please provide more details about an option where you suggested to draw polygon graphics in a GraphicsOverlay?**
Ex. How do we handle pixel colors?

**Could you please provide the exact API name(or reference) for the same?**

**Can you share some examples available, if there are any?**

Any help would be really appreciated!
