### ISSUE TITLE
Is it possible to draw custom objects(like smoke) on top of ArcGIS earth environment?

### ISSUE THREAD

**Issue by shrikant-panchal** [Esri/arcgis-runtime-samples-qt#1058]
My question is in continuation of following  issue,
https://github.com/Esri/arcgis-runtime-samples-qt/issues/1050#issue-603075995 

I tried to put a query on "Geonet" portal 4-5days back, but did not receive any response yet. Sorry, but this is quite an urgent requirement and your inputs will really help us take a better decisions.

Could you please provide more details about an option where you have suggested to draw polygon graphics in a GraphicsOverlay?
Ex. How do we handle pixel colors?

Could you please provide the exact API name(or reference) for the same?

Can you share some examples available, if there are any?

Any help would be really appreciated!

**Comment by ldanzinger** [comment]
Can you please paste the link to the geonet post? I don't see anything in the Qt SDK space - https://community.esri.com/community/developers/native-app-developers/arcgis-runtime-sdk-for-qt

**Comment by shrikant-panchal** [comment]
Thanks Lucas!
I have raised a  query on the geonet portal once again.
But as I mentioned, it's quite an urgent requirement and this query is the crucial point for us to make a decision.
So I would request you to help us with the required information ASAP.

**Comment by ldanzinger** [comment]
@shrikant-panchal - we will do our best to help you, but if you have urgent requests that need assistance ASAP, your best bet is to utilize [Esri Support Services](https://support.esri.com/en). They are dedicated to assisting customers and helping them resolve their urgent cases. The community (and development team) is here to help and offer suggestions but can make not guarantees in response time. I will discuss your query with the team and reply on the GeoNet post, but we are in the final days of release certification testing and cannot guarantee a speedy reply.
