### ISSUE TITLE
failed to find local server

### ISSUE THREAD

**Issue by MohamedElfeky** [Esri/arcgis-runtime-samples-qt#1088]
when try to start local server button 
the debugger output : 
Starting server
Failed to find local server runtime in the following location(s):
/64/bin

**Comment by ldanzinger** [comment]
Are you using version 100.8? Local Server 100.8 is not released yet, but planned to be released soon - https://www.esri.com/arcgis-blog/products/developers/announcements/welcome-to-arcgis-runtime-100-8/

**Comment by MohamedElfeky** [comment]
yes, i use this version so which Version support ? 
my app is fully disconnected desktop app using qt c++ only so what the best way you recommend .
i read about tile cache and tiled layer but i don't know the way to download it to my app 
thanks a lot,

**Comment by ldanzinger** [comment]
@MohamedElfeky 100.8 Runtime will work with 100.8 Local Server, however, it is not released yet. It should be released in the next week or so.

I'd suggest waiting until it is released OR installing 100.7 of Runtime SDK and 100.7 version of Local Server.
