### ISSUE TITLE
Runtime Local Server: Input Feature Set is shown as GPString not as Feature Set?

### ISSUE THREAD

**Issue by esride-jts** [Esri/arcgis-runtime-samples-qt#1170]
We tried to use the Local Server GP Sample with a ArcGIS Pro based Geoprocessing Package having features as input parameter. The local server shows the feature input parameter as GPString.

We could not reproduce this in ArcMap 10.8.1. Is ArcGIS Pro creating incompatible Geoprocessing Packages? Any help would be appropriated.

The complete discussion:
[Runtime Local Server: Input Feature Set is shown as GPString not as Feature Set?](https://community.esri.com/t5/arcgis-runtime-sdk-for-qt/runtime-local-server-input-feature-set-is-shown-as-gpstring-not/m-p/1003882#M3838)

**Comment by ldanzinger** [comment]
I've looped in Mike Branscomb who has commented on the GeoNet post. Let's continue the discussion there since it is a question about Local Server/Pro publishing functionality, not so much the sample itself.
