### ISSUE TITLE
BuildLegend demo crashes on startup

### ISSUE THREAD

**Issue by markdeaton** [Esri/arcgis-runtime-samples-qt#1279]
When I run the [samples app](https://www.arcgis.com/home/item.html?id=b5e3fb57de0348d8bd919947730dd956) and switch to the [BuildLegend ](https://github.com/Esri/arcgis-runtime-samples-qt/tree/main/ArcGISRuntimeSDKQt_QMLSamples/DisplayInformation/BuildLegend)demo, the entire app crashes and disappears.
This happened on a Samsung Galaxy S10+ running Android 11.

I see this error in the LogCat:
2021-08-11 12:03:21.661 13887-15075/com.esri.arcgisruntime.ArcGISRuntimeSDKQt_QMLSamples A/libc: Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x8 in tid 15075 (qtMainLoopThrea), pid 13887 (DKQt_QMLSamples)

**Comment by ldanzinger** [comment]
Hi @markdeaton - this issue is related to one of the services being down. We have a fix in our 100.12 release to handle this scenario. 100.12 should be released next week or the week after
