### ISSUE TITLE
Error while running TileCacheLayer in arcgis-runtime-samples-qt

### ISSUE THREAD

**Issue by kunalkhosla93** [Esri/arcgis-runtime-samples-qt#1345]
While running TileCacheLayer on Qt, I got the blow error-

C:\Users\HP\Downloads\arcgis-runtime-samples-qt-main\arcgis-runtime-samples-qt-main\ArcGISRuntimeSDKQt_CppSamples\Layers\build-TileCacheLayer-Desktop_Qt_5_12_12_MSVC2015_64bit-Release\release\TileCacheLayer.exe crashed.

The project was built successfully but there is a problem while running.

Below are the Qt details:

Compiler: Qt_5_12_12_MSVC2015
Based on: Qt 5.15.2
Qt Creator 5.0.2

**Comment by JamesMBallard** [comment]
@kunalkhosla93 what version of the Runtime are you using? With our previous few releases, they all require Qt 5.15.2 minimum and MSVC 2019 on Windows. It could be a Qt and/or compiler toolchain mismatch with our minimum requirements.

**Comment by kunalkhosla93** [comment]
Hi, i was unable to check as i am away from my device. But is it somehow possible to view offline tiled maps (downloaded in a directory) using one of the projects here. If so, kindly help me with the correct project name. Meanwhile ill check the requirements.

Thank you once again:)
