### ISSUE TITLE
Viewing offline tiled maps in Qt

### ISSUE THREAD

**Issue by kunalkhosla93** [Esri/arcgis-runtime-samples-qt#1348]
Is it somehow possible to view offline tiled maps (downloaded in a directory {/z/x/y.png} ) using one of the projects here. If so, kindly help me with the correct project name. 

Thanks

**Comment by ldanzinger** [comment]
We don't have a project available, but we have a code snippet in our API reference - https://developers.arcgis.com/qt/cpp/api-reference/esri-arcgisruntime-serviceimagetiledlayer.html

**Comment by tanneryould** [comment]
We've opened an issue in our common samples repository to evaluate adding a "View offline tiled maps" sample to the Runtime SDK samples.
