### ISSUE TITLE
Missing include

### ISSUE THREAD

**Issue by NorbertThoden** [Esri/arcgis-runtime-samples-qt#372]
example 'ArcGISRuntimeSDKQt_CppSamples/Scenes/BasicSceneView/main.cpp'

There is an include missing:  #include <qqmlengine.h>

**Comment by ldanzinger** [comment]
Thanks @NorbertThoden. In case you have already fixed it locally, we also gladly accept pull requests 😃

**Comment by NorbertThoden** [comment]
Hi!
I need the example just to be added to a support call.
Therefore i  didn´t clone the repo.

I am sure that Esri is able to process it in this way.

BTW, has someone ever tested these examples?
After the release of V100.0?
On a os which is case sensitive?

I don´t think so. 
The reason: There is a mix of defining some paths

For example: dataPath is often defined '/ArcGIS/Runtime/Data
But the installer will install it to /arcgis/runtime_sdk...
So many example will not run :-(

Best regards

**Comment by michael-tims** [comment]
>  For example: dataPath is often defined '/ArcGIS/Runtime/Data, But the installer will install it to /arcgis/runtime_sdk...

@NorbertThoden These are not meant to be the same folder by design.  Of course you could always modify the same code locally if you wish to store the data in a separate path.

**Comment by NorbertThoden** [comment]
Hi Michael!
Good to hear from you!

not intended? Sounds strange to me.
Why?
Image a user installs the sdk and clones the github to start with an example.
On windows the example will find the file stored at dataPath, on linux not....
My conclusion: the github example does not really fit to the sdk installer....
(think of the stylx-file, won`t be found due to different paths...
I can´t believe that this what you like to achieve...

But, there are additional problems: 
A couple of files are NOT in the github: mil2525dmesage.xml...
For me it´s difficult to find them.
Hopefully i won´t have to run such an example (to use that as an example for the official support call).


Thank you

**Comment by ldanzinger** [comment]
@NorbertThoden this include is now added. Thanks for bringing to our attention!

**Comment by michael-tims** [comment]
@NorbertThoden Looks like @ldanzinger answered most of your questions here:  https://github.com/Esri/arcgis-runtime-samples-qt/issues/367

So in summary, the README for each example should note where you can download the data from.  Then you can place it wherever you like and update the code to point to the dataPath you prefer.
