### ISSUE TITLE
vNext branch: Bug with speed slider on Animate3DSymbols samples (C++ and QML)

### ISSUE THREAD

**Issue by mgayheart1** [Esri/arcgis-runtime-samples-qt#509]
The interval property of Timer in Animate3DSymbols.qml should use Math.max instead of Math.min. Right now, the speed is always 1 no matter where the slider is positioned unless the slider is all the way to the right at which point it is 0. This is a bug in both the QML and CPP samples. 
Instead of:
```
Timer {
        id: timer
        interval: Math.min(animationSpeed.maximumValue - animationSpeed.value,1);
        running: playButton.checked;
        repeat: true
        onTriggered: animate(animationSpeed.value);
    }
```

It should be:
```
Timer {
        id: timer
        interval: Math.max(animationSpeed.maximumValue - animationSpeed.value,1);
        running: playButton.checked;
        repeat: true
        onTriggered: animate(animationSpeed.value);
    }
```

**Comment by lsmallwood** [comment]
@mgayheart1 - thanks for reporting. A fix for this issue has been merged.
