### ISSUE TITLE
GenerateOfflineMap sample doesn't work.

### ISSUE THREAD

**Issue by E-genin** [Esri/arcgis-runtime-samples-qt#671]
Hi there,

I'm trying to generate an offline map using GenerateOfflineMap qml example, the problem is that when I run the program, a window pops up with no content and I get this in QtCreator's application output: 

`QML debugging is enabled. Only use this in a safe environment.
Esri.ArcGISRuntime.Plugin: virtual void ArcGISRuntimePlugin::registerTypes(const char*) Esri.ArcGISRuntime
Esri.ArcGISRuntime.Plugin: static void QmlUtils::registerTypes(const char*) Esri.ArcGISRuntime
Empty filename passed to function
Empty filename passed to function`

Can you tell me what's exactly the problem.

**Comment by ldanzinger** [comment]
@E-genin we have seen that error starting with Qt version 5.10, but have not noticed any side effects, so I'm wondering if there is another issue going on. What version of Qt and which platform are you on? Do any of the samples work (like [Display A Map](https://github.com/Esri/arcgis-runtime-samples-qt/tree/master/ArcGISRuntimeSDKQt_QMLSamples/Maps/DisplayMap))?

**Comment by E-genin** [comment]
Hi, Thanks for the reply !

I'm working on Qt5.10.1 in Linux Ubunto 16.04.

**Comment by E-genin** [comment]
Any Answer !!

**Comment by ldanzinger** [comment]
I believe you need to uncomment the following lines so that the AuthenticationManager can issue a challenge to you so you can sign in - https://github.com/Esri/arcgis-runtime-samples-qt/blob/master/ArcGISRuntimeSDKQt_QMLSamples/Maps/GenerateOfflineMap/GenerateOfflineMap.qml#L197-L202

**Comment by E-genin** [comment]
Right, it works now but where can I find the Generated map ?

**Comment by ldanzinger** [comment]
It goes to your temp folder - https://github.com/Esri/arcgis-runtime-samples-qt/blob/master/ArcGISRuntimeSDKQt_QMLSamples/Maps/GenerateOfflineMap/GenerateOfflineMap.qml#L30

You could console.log() that variable and see where exactly that is on your system

**Comment by ldanzinger** [comment]
Closing this issue out, as I believe the AuthenticationManager commented lines were the issue. Please reopen if not the case. Thanks!

**Comment by csumit249** [comment]
cannot resolve this error in display a map tutorial arcgis for qt
Initializing application
Esri.ArcGISRuntime.Plugin: virtual void ArcGISRuntimePlugin::registerTypes(const char*) Esri.ArcGISRuntime
Esri.ArcGISRuntime.Plugin: static void QmlUtils::registerTypes(const char*) Esri.ArcGISRuntime
qt.network.ssl: QSslSocket: cannot resolve EVP_PKEY_base_id
qt.network.ssl: QSslSocket: cannot resolve SSL_get_peer_certificate
Device supports OpenSSL:  true
qt.network.ssl: QSslSocket: cannot call unresolved function SSL_get_peer_certificate
