### ISSUE TITLE
looks like a bug in API.

### ISSUE THREAD

**Issue by Girishchandra-Yendargaye** [Esri/arcgis-runtime-samples-qt#947]
Hello Team,

I have created a Dockable widget class and created map_view in it.

Its loading properly.

But when I double click to dock it out map view is coming as blank black screen.

Thanks,

**Comment by JamesMBallard** [comment]
Hi @Girishchandra-Yendargaye. Thanks for bringing this to our attention. We can reproduce this problem on our end and are hoping to prioritize fixing this issue for an upcoming release.

**Comment by ldanzinger** [comment]
This should be fixed in out 100.8 release, which is coming out in the next week or two.
