### ISSUE TITLE
includes missing

### ISSUE THREAD

**Issue by Kyeiv** [Esri/arcgis-runtime-samples-qt#948]
Hello, running RasterLayerFile my project is missing:
#include "Map.h"
#include "MapQuickView.h"
#include "Raster.h"
#include "RasterLayer.h"
#include "Basemap.h"

i cloned the repo and launched .pro file in QtCreator, is something that i did not but had to?

**Comment by ldanzinger** [comment]
Those files are included in the cpp - https://github.com/Esri/arcgis-runtime-samples-qt/blob/master/ArcGISRuntimeSDKQt_CppSamples/Layers/RasterLayerFile/RasterLayerFile.cpp#L19-L23

Did you make sure to install the SDK following the Guide? https://developers.arcgis.com/qt/latest/qml/guide/install-and-set-up-on-windows.htm
